# Generated by Django 3.2.11 on 2022-01-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_alter_receita_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='tipo_renda',
            field=models.IntegerField(choices=[(1, 'Fixa'), (2, 'Variavel')], default=1, verbose_name='Tipo de renda'),
        ),
    ]
