# Generated by Django 3.2.11 on 2022-01-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='type',
        ),
    ]
