# Generated by Django 3.2.11 on 2022-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FO', 'Food'), ('HE', 'Health'), ('HO', 'Home'), ('TR', 'Transport'), ('ED', 'Education'), ('LE', 'Leisure'), ('UN', 'Unforeseen'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
